SHOW DATABASES;
USE sqlpractise;
describe sqlpractise;
SHOW TABLES;
describe department;
describe emp_details;
describe employee;
SELECT* FROM employee;
SELECT* FROM department;
SELECT Emp_Name,Dept_Name from employee as e inner join department as d on Dept_Name = 'Finance';
Select count(*),Dept_Name from employee as e inner join department as d group by Dept_Name;
Select count(employee) as Id, Dept_Loc from employee as e inner join department as d on Dept_Loc ='Jigani';
Select Emp_Name from employee as e inner join department as d on Emp_Exp_Yrs > 10 and Dept_Loc = 'Jigani';
Select Dept_Name from employee as e inner join department as d order BY employee DESC LIMIT 1;
ALTER TABLE employee ADD salary integer;
UPDATE employee SET salary = 300000 WHERE employee = 1; 
UPDATE employee SET salary = 100000 WHERE employee = 2; 
UPDATE employee SET salary = 400000 WHERE employee = 3; 
UPDATE employee SET salary = 300000 WHERE employee = 4;
UPDATE employee SET salary = 350000 WHERE employee = 5;
UPDATE employee SET salary = 380000 WHERE employee = 6;
UPDATE employee SET salary = 300000 WHERE employee = 7;
UPDATE employee SET salary = 3000 WHERE employee = 8; 
UPDATE employee SET salary = 300000 WHERE employee = 9; 
UPDATE employee SET salary = 37000 WHERE employee = 10; 
SELECT Emp_Name,salary FROM employee WHERE salary < (SELECT avg(salary) FROM employee); 